### ISSUE TITLE
Sound crackling

### ISSUE THREAD

**Issue by rayabusa** [dborth/snes9xgx#720] opened 2018-04-01 13:41 UTC
Sound is crackling  on a lot of games, maybe a sync issue

**Comment by askotx** [comment] 2018-04-01 16:16
Check your settings and give more info.

**Comment by rayabusa** [comment] 2018-04-01 16:28
my settings are:

original resolution 240p via component
4:3 default
video mode automatic (NTSC)
super FX default
classic pro controller

the crackling are more frequent when playing rom hacks or translated roms but happens with normal games too.

**Comment by Nashismo** [comment] 2018-04-20 06:29
It is the same problem I am having, actually my issue is just below yours :P and this is also using 4.3.7 version of the emu, and your exact same settings.

One thing to note is that this does NOT happen in let's say Snes9x on RetroarchWii. The problem is that Snes9x Retroarch Wii is very slow! Super FX games dont work fullspeed at all in there.

This emulator is so good and fast, that is honestly a shame that this problem keeps ocurring.

**Comment by bladeoner** [comment] 2018-07-29 17:43
@rayabusa @Nashismo [Snes9x.GX.New.zip](https://github.com/dborth/snes9xgx/files/2239024/Snes9x.GX.New.zip)

**Comment by dborth** [comment] 2018-08-14 03:10
Here's a beta, maybe it's better?
[Snes9xGX-4.3.8-Beta2.zip](https://github.com/dborth/snes9xgx/files/2285356/Snes9xGX-4.3.8-Beta2.zip)

**Comment by Nashismo** [comment] 2018-08-14 03:53
Tested it. Mostly on Chrono Trigger (the game were the issue is more easy to recreate).

And yes, it is better, much less of that garble crackling sound, but instead we have the audio skipping forward, is like it goes fast forward in order to stay in sync, it is a different issue, but I believe it is better than the audio noise.

It is a step in the right direction I think. Thanks dborth.

**Comment by dborth** [comment] 2018-08-14 17:27
[Snes9xGX-4.3.8-Beta3.zip](https://github.com/dborth/snes9xgx/files/2287922/Snes9xGX-4.3.8-Beta3.zip)

Thanks for testing. Here's another beta. Hopefully this is at least as good as the last if not better. Let me know.

**Comment by dborth** [comment] 2018-08-14 21:18
[Snes9xGX-4.3.8-Beta4.zip](https://github.com/dborth/snes9xgx/files/2288514/Snes9xGX-4.3.8-Beta4.zip)

Thanks for testing. Here's another beta. Hopefully this is at least as good as the last if not better. Let me know.

**Comment by dborth** [comment] 2018-08-15 02:31
What game did you hear the crackling on? Can you post a snapshot here I can resume from so I can look at it?

**Comment by Nashismo** [comment] 2018-08-15 02:39
Like always, Chrono Trigger (US) beginning of the game and when entering in and out of menus (anywhere in the game). That's when the music always tends to stutter or when any given audio issue occur.

I always use that game to test audio on snes emulators :) 

The same game on Retroarch Wii snes9x runs flaelessly. It is a shame really, because like I said before this port is really fast! (Maybe thats the problem?)

Cheers and thanks againg dborth

**Comment by dborth** [comment] 2018-08-15 20:54
[Snes9xGX-4.3.8-Beta5-156-core.zip](https://github.com/dborth/snes9xgx/files/2291668/Snes9xGX-4.3.8-Beta5-156-core.zip)
[Snes9xGX-4.3.8-Beta6-hybrid-core.zip](https://github.com/dborth/snes9xgx/files/2291670/Snes9xGX-4.3.8-Beta6-hybrid-core.zip)

Here's two more betas.

**Comment by Nashismo** [comment] 2018-08-16 01:08
Beta6 Hybrid, that did it! Cant believe it! No more stuttering music or sounds!

I played the game over and over because I couldnt believe it at first. But yes, it is working pretty nice :)

Only thing I notice is a higher pitched sound (bad lows mostly). But that could probably be fixed with an equalizer option in the future! ;) 

Or maybe the real Snes had bad lows and the emu is just being accurate? Maybe.

Again. Dborth you are the man! You made me feel really happy with this and I am sure many people will be super glad too!

Cheers from Chile friend!

**Comment by dborth** [comment] 2018-08-16 01:25
Was this sound distortion present on 4.3.7 too? I adjusted the playback rate so perhaps that's the cause.

**Comment by Nashismo** [comment] 2018-08-16 01:38
Tesed 4.3.7 to have a clear memory. And no, no sound distortion in 4.3.7 still the lows arent great but there is no sound distortion at all in 4.3.7

**Closed** 2018-08-16 20:05 UTC

**Comment by dborth** [comment] 2018-08-17 19:48
[snes9xgx-beta-156-sound-core.zip](https://github.com/dborth/snes9xgx/files/2298512/snes9xgx-beta-156-sound-core.zip)

Just curious, is the sound on this beta the same, different, better, worse?

**Comment by Nashismo** [comment] 2018-08-17 23:46
Dborth sound is better, no distortion! (Chrono Trigger bells, etc) Better lows, not as punchy as Retroarch snes9x but better than before!

The only problem is that the games hang (black screen) after 5 minutes of playing or so.

I couldnt check for sound crackling because of the hangs, but it was good the minutes I could play. A stable version of this one would be something nice.

Thanks for your time dborth! You are almost there in building the ultimate Snes emulator out there (240p, fx games, good speed, good sound).

Againg thanks for using your time to do this.
