### ISSUE TITLE
madden nfl 96 wont load

### ISSUE THREAD

**Issue by supersonicjc** [dborth/snes9xgx#864] opened 2019-06-26 07:30 UTC
so im trying to get the madden nfl 96 to load up and I keep getting a black screen and nothing else, im using the current build as of april 19, game worked fine in past builds and works with no issues on the snes9x emu on pc current build, not sure what is going on if there is a chip missing or what have you, also worth noting is that all other years of the madden games (94 to 98) do load its just this particular rom isn't working

**Comment by supersonicjc** [comment] 2019-06-27 10:34
so 2 more games with the same issues, emmit smith football and college football 97 all 3 games give me a black screen, I was able to get college football to load once and it gets me to the ea slash and crashes?? or freezes?? not sure whats going on there, all my roms are good and all 3 work just fine on pc emulator no issues

**Comment by bladeoner** [comment] 2019-07-02 21:28
I don't how many time a go you tested it with Snes9x GX but the issue is there for years. Tested it with several versions and noticed that 4.1.5 is the latest version it worked with, so between 4.1.5. and 4.1.6 lays the problem. Since 4.1.6 the core was updated to Snes9x 1.52 and we are using 1.60 now, I'm not sure if this issue can be fixed.

**Comment by dborth** [comment] 2019-07-03 01:26
Thanks for investigating bladeoner, this is a snes9x issue. Closing.

**Closed by dborth** 2019-07-03 01:26 UTC
