### ISSUE TITLE
Tengai Makyou Zero

### ISSUE THREAD

**Issue by wolfniggr** [dborth/snes9xgx#750] opened 2018-09-15 15:27 UTC
Tengai Makyou Zero no longer works in 4.3.9.  When loading, it stays on a black screen.  Save state will load, but you are not able to move.

**Comment by supersonicjc** [comment] 2018-09-15 21:45
chou aniki  bakuretsu rantou hen doesn't work either, it did work on the core upgrade to 1.56, wonder if the owner would be able to make at least 1.55 core to work and not break the games as badly

**Comment by bladeoner** [comment] 2018-10-15 19:34
@wolfniggr does the problem with the black screen occur with the English patched Japanese rom?

I could reproduce the issue with the rom above, I made some changes in the code which seems to work without upgrading the core to 1.55 or 1.56.

Could you please test my attached version of Snes9x GX and post your feedback so I can create a Pull Request.

Thanks in Advance.

[Snes9x.GX.Test.zip](https://github.com/dborth/snes9xgx/files/2480253/Snes9x.GX.Test.zip)

**Comment by supersonicjc** [comment] 2018-10-15 20:16
@bladeoner so I had some free time and tested this out for you, tengai makyou zero worked for me with this beta, oddly enough tho the unpatched rom gave me a save file of 1996 even tho the patched translation gave todays date, also not sure if you were working on it or not but chou aniki still doesn't work with this beta
hope this helps you out also love the new music personally would of gone with stickerbrush symphony but still good

**Comment by bladeoner** [comment] 2018-10-15 20:20
@supersonicjc thank you for your feedback I am not working on Chou Aniki but I also could reproduce that problem.

For Tengai Mayou Zero I will make a PR.

**Comment by bladeoner** [comment] 2018-10-16 11:55
@supersonicjc with this test version both games should work:
[Snes9x.GX Test2.zip](https://github.com/dborth/snes9xgx/files/2482876/Snes9x.GX.Test2.zip)

**Comment by supersonicjc** [comment] 2018-10-16 23:07
@bladeoner yes the game now loads up and the other one works too, only real issue im finding right now is when im trying to speed up in this beta build the right stick doesn't always register the command, other then that thank you for still working on this awesome emulator

**Comment by bladeoner** [comment] 2018-10-17 10:10
> @bladeoner yes the game now loads up and the other one works too, only real issue im finding right now is when im trying to speed up in this beta build the right stick doesn't always register the command, other then that thank you for still working on this awesome emulator

@supersonicjc don't put a lot of time in the controller not working correct, it's because I reverted the controller fix otherwise my controller is not working. If the PR for Chou Aniki is merged with the source it should not give any problems for you.

**Comment by bladeoner** [comment] 2018-10-17 16:38
@wolfniggr I looked into the problem with the Real Time Clock but that is not possible to fix at this point.

The only way is to upgrade the core and that comes with some other issues.

For now I think it's best if you keep using the version that you already have.

**Comment by wolfniggr** [comment] 2018-10-17 18:04
@bladeoner That's too bad.  For a while, this was the easiest emulator to get this game to work with(no additional files were needed unlike the other 2 emulators that could also run this rom)  Thanks for giving it a try.

Just out of curiosity, what are the benefits to reverting the core?

Thanks, again for all your help.

**Comment by bladeoner** [comment] 2018-10-18 13:28
@wolfniggr the version that you are using, did you build it yourself?
If so do you remember at which commit you build it?

Thanks in advance.

**Comment by wolfniggr** [comment] 2018-10-19 19:44
@bladeoner I didn't build it myself. I do remember getting it a few days before 4.3.8 went up on this site. I just assumed I got the build of that version early. Now that I look at it, I realize it's not.  I'm sorry, but I don't remember where I found it. (I'll reply if I come across it again)

I had a custom version of 4.3.7 prior to that I downloaded from a link in a YouTube video to play ver.7 of the patched rom released in July.  Unfortunately the link is dead, but I'm sure you could comment to request an updated link if that helps.  https://www.youtube.com/watch?v=2FPYAY5n0FA

**Comment by bladeoner** [comment] 2018-10-23 16:32
Thank you for your reply I asked the author of the patch if he could provide me more information.

**Comment by bladeoner** [comment] 2018-10-25 09:43
@wolfniggr the issue has been addressed its not in the snes9x gx source code but in the tools to compile the source. Later I will share it with a working clock.

I also made a build with a 1.56.2 core and all the commits I will compile that later, its experimental but you can test it if you want to compare.

**Comment by wolfniggr** [comment] 2018-10-25 15:48
@bladeoner I'd be willing to test that build.

You mentioned your new build will be based on a 1.56.2 core.  Will a working build using the 1.52 core be possible?

Thank you

**Comment by bladeoner** [comment] 2018-10-25 18:09
@wolfniggr the file below is just the latest master (4.3.9) with the real time clock fixed, which is using 1.52 core:
[Snes9xGX_4.3.9_RTC_Fixed.zip](https://github.com/dborth/snes9xgx/files/2516166/Snes9xGX_4.3.9_RTC_Fixed.zip)

And the file below is an experimental version I was working on with all commits included and based on 1.56.2 core. I added three new functions:
- CPU Overclock
- Sprite limit, normally it limits the sprites per line to 34, this takes the maximum to 128
- And I got the superFXoverclockmultiplier working
[Snes9xGX_4.4.0_experimental_core_1.56.2.zip](https://github.com/dborth/snes9xgx/files/2516177/Snes9xGX_4.4.0_experimental_core_1.56.2.zip)

**Comment by wolfniggr** [comment] 2018-10-26 00:52
@bladeoner this is great. I’ll test them out this weekend. 

Thanks, again for all your work. I’ll let you know how it goes

**Comment by wolfniggr** [comment] 2018-10-26 22:45
@bladeoner both versions seem to run Tengai Makyou Zero fine.  Clock seems to work correctly now.

I tested other games to see how both versions handled them(Road Avenger, Starfox 2 and a few others).  It looks like Chou Aniki doesn't work properly on either version you attached.  All seems fine until the end of the first round. Once it goes dark, it stays that way with the music still playing in the background.  I'm not a fan, but I thought I'd let you know since someone mentioned it earlier in this thread.

Not sure what the cpu overclock does. I tried to see if it improved Street Fighter Zero 2, but it ran exactly the same.

Apart from that, everything seems to run great.
Let me know if you want me to test a specific game or if you need any more info.

Thank you

**Comment by bladeoner** [comment] 2018-10-28 09:32
@wolfniggr thank you for your feedback.

Regarding Tengai Makyou Zero and the timestamp, yesterday I spoke to someone who helped me with the RTC. The clock is working but the date not I was playing Tengai and the date didn't change.

I am busy with a new beta (based on core 1.56.2) were I compiled snes9x with older tools which should solve the date problem, you can download it here in my second post:
https://gbatemp.net/threads/snes9x-gx-4-4-0-beta-feedback-requested.521929/

The extra features from the version I shared here are not in it anymore it has SuperFX Overclock like the stable version.

Changelog:
- Update the core to 1.56.2 again.
- Applied all commits which came out after reverting core 1.56.2 to 1.52.
- Got the SuperFX Overclock feature working for games like Yoshi's Island and Star Fox.
- Backported all changes from the snes9x master branch.

Could you test this version to see if all works nornal with the games you mentioned? Especially Tengai Makzou Zero and Chou Aniki I'm curious about.

Thanks in advance.

**Comment by bladeoner** [comment] 2018-10-28 21:37
The date problem lays in the tools to build snes9x gx:
https://github.com/devkitPro/libogc/issues/59

The version I gave you with the extra options was just to test, for now there is nothing else to test.

Thank you.

**Comment by supersonicjc** [comment] 2018-10-29 02:29
@bladeoner I had some free time so I went and tried this build out, tengai makyou zero seems to run just fine with little to no real issues as far as I can tell, chou aniki plays til the first match ends then just get music and black screen (tested out on pc and should go to round 2 and so on til match ends) not sure what is going on there, star fox 1 with the new build there is lag that really drags the game down, Yoshi island there is screen tearing going on with the new build, other fx chip games seem so far ok, contra 3 I swear that the first boss didn't have the type of screen tearing effect going on with it on prior builds but I read in a closed issue that its game related?? not sure whats going on there (like the mode 7 isn't doing the sprite scaling correct or something??) star fox 2 sounds like its lagging behind but honestly can only test that with the rom that's in the classic mini as its an unofficial dump that's running but in theory it should have the fx chip or something similar to smw2 or smrpg with the chips, all the game saves are coming up as correct time stamps but im sure that was what you made in the build, kinda miss the aquatic ambience that you had on your earlier test builds even tho I would prefer having stickerbrush symphony, other then that most the games I played around with seem ok as long as they didn't have special chips as most of the latter half of the system games came with, maybe the wii cant run it fully with the more accurate emulators even tho im running mine on the wii u wii mode?? since you got the fix on chou aniki to boot the game is there maybe some programing magic to get it to stay running and not go to black screen after the 1st match??? I know that game isn't that advanced and I know it worked on older versions in the past, thanks for the work

**Comment by bladeoner** [comment] 2018-11-03 09:39
@supersonicjc thank you for your feedback.

I was working on another build with core 1.56.2 but the conclusiin is the Wii hardware is nit sufficient:
https://gbatemp.net/threads/snes9x-gx-4-4-0-beta-feedback-requested.521929/

Gooed to hear Tengai Makyou Zero and the save date works. 
To fix the save game date I build the source with devkitpro r30 and libogc 1.8.19. 

When I have some time I will check Chou Aniki's black screen after the first round.

**Comment by bladeoner** [comment] 2018-11-07 05:09
@supersonicjc yesterday I was testing to modify the settings necessary to get Chou Aniki working to see if that helps with the black screen after the first round but that didn't solve the problem.

**Comment by supersonicjc** [comment] 2018-11-17 16:00
@bladeoner I know that the game worked just fine when the core was 1.51 and I could play it just fine on the pc for that version as well, plus I can play on my pc just fine with the core 1.56, I haven't tried the game out just yet on core 1.57 mainly as I didn't know they dropped a new core and have been busy but I know for a fact I am able to play it on my pc with 1.56, im going to look back and test the game again on a build that was prior to core 1.52 if I can find it cause I do know it worked on the snes9xgx and I know it plays on my pc

**Comment by supersonicjc** [comment] 2018-11-17 19:20
@bladeoner so I went back and tested older versions and the last version that the game did work but not without other issues was 4.1.6 when the cheats were iffy the next version 4.1.7 wouldn't load for me
4.1.8 just crashed the system, 4.1.9 onwards the game would only load a black screen some versions had some interesting issues all on there own but those would get fixed later on, version 4.1.5 was running was core 1.51 and 4.1.6 was the newly introduced core 1.52 so surprisingly it did work on core 1.52 I played it up to 4 matches and it worked just fine, after that nothing until your betas where you got only round 1 to work, so im really at a loss now as to what changed, I will look for the pc 1.57 to see if I get it to play for me and hope it will get working soon

**Comment by supersonicjc** [comment] 2018-11-17 21:55
@bladerner ok so I found the new core to run on the pc 1.57 and I keep getting different results here along with older version 1.55 where the game will randomly freeze at different levels 1 game play I got to match 8 round 2 and another time I got to match 2 round 1 where I would get the black screen I know the rom itself is a good dump so im not sure what is going on as I cant find any info on if there was any special chips (super fx or sa1) running with the game, so with that in mind im at a total loss here as to what is going on, I can however confirm that I was able to play all the way through on 1.51 to the credits with no issues other then the fact that emu is way outdated so im really at a loss with what the issue is with this game??

**Comment by supersonicjc** [comment] 2018-11-18 20:07
@bladeoner maybe this could help out https://github.com/snes9xgit/snes9x/issues/187 it seems that there was a bug introduced in the original core for 1.52 and they didn't address it until 1.55 which seems logical there since it looks like they were trying to fix there mixup, honestly would of said something sooner but it really is one of those hidden gem kinda games there

**Comment by bladeoner** [comment] 2018-11-20 12:22
@supersonicjc the fix mentioned in the post is the one I applied to get the game working, I didn't found any other clue why it's not working correct. As mentioned before I tried different settings on that change and some other settings as well when I was working on core 1.57 but I couldn't get it to work properly.

Since it's also in snes9x in Windows there I'm really clueless.

Did you try for example Higan or Bsnes to see if the problem occur?

**Comment by bladeoner** [comment] 2018-11-20 17:40
@supersonicjc see the response of bearoso https://github.com/snes9xgit/snes9x/issues/452 there is not a lot we can do.

**Comment by supersonicjc** [comment] 2018-11-20 17:57
@bladeoner I seen the response but not sure how an official game is a ill conceived hack??? anyway you wrote that it eventually loads?? is that mean that its just not catching the right line of code to continue on after a match? so im guessing that it works but only til a match is done then?? o well at least it works I guess, its one of those very unique games that most don't even know exist, do what you can I guess

**Comment by bladeoner** [comment] 2018-11-20 20:32
He is not referring to the game the change made to get past the black screen when starting the game that is applied is a timing hack. It seems it's really difficult to get the correct timing to get the game running properly. I think this problem was already there in the older versions of the emulator but less noticeable. From that time until now a lot of code has been changed so I guess that made it more noticeable that there is a timing issue.

**Comment by supersonicjc** [comment] 2018-11-20 21:58
I relooked at his answer now that I had coffee lol, it seems that he relooked at it as he was thinking of another game with an English translation that doesn't work on more accurate emulators which honestly the game hes talking about I have an older less accurate translation that does work... he reopened the issue and it seems that there is a timing issue there and more technical talk that im not fully understanding there, it seems he adjusted the cpu and apu differently to make the gaming clock work better, fingers crossed if what hes talking about works to fixing this game

**Comment by bladeoner** [comment] 2018-11-21 06:29
@supersonicjc Thank you for your reply.

Just like I said in my last reply here a timing issue. I will wait for the confirmation what to change and test.

**Comment by bladeoner** [comment] 2018-11-21 12:58
For me it didn't work, after the second round I get the same issue.

**Comment by bladeoner** [comment] 2018-11-23 14:37
@supersonicjc did you hear the stickerbrush symphony? 😊 Yesterday I tried to increase the opcode cycles to make it equal to snes9x. In snes9x gx we use 3 opcycles and in snes9x 5 but also to make it the same as snes9x so 5 I ended up a black screen after the first fight. I don't know what is causing this.

**Comment by supersonicjc** [comment] 2018-11-24 20:36
@bladeoner I did and it was amazing, so curious what did you have that beta set at for my testing?? would possibly running it faster then 3 or 5 maybe make a difference?? I did see they merged your issue from the main emu to a trouble shoot from 2 years ago and had corrections to it so it really must of been something they changed when they made the emu more accurate and possibly this game wont run on the more accurate which is sad..... I honestly thought I almost had it figured out the other night when I tested it out some more but man is this game tricky to figure out as like I said before almost a requirement for you to be attacked by the cpu before you could attack seems very sad as you couldn't obtain a perfect ie street fighter or mortal kombat, but then again it doesn't matter as there isn't any scoring system as far as I can tell lol, on slightly better news I got the game to run on pc emu just fine on core 1.55 and the new core 1.57 altho I don't like the new pc core as it really messes up the cheat code files especially when you try to go back to older cores but that is moot point as most of the time you go to newer instead of older sans the case of some of the older hacks I play that are broken in newer emulators as they weren't designed for accurate gaming, any way to get the changed beta that you were working on for me to test?? or maybe overclock on one and underclock the other??? not that good on pc lingo here

**Comment by bladeoner** [comment] 2018-11-29 06:51
The beta I was working on was to update the core to 1.57 that has been done.

I tested to increase the value to 7 but the same results black screen.

On 1.57 on the pc you can get through all rounds?

**Comment by supersonicjc** [comment] 2018-11-29 08:31
so tested on pc, could only get the 4th character to advance levels by these strict requirements,
1 cant press any buttons til after the cpu hits you
2 required to let the cpu attack and connect 
3 forced to wait til the cpu attack is finished
4 the moment the match is called stop pressing buttons
5 repeat steps 1 to 4 on next match or game will freeze

was only able to get this consist with the 4th character and all others would freeze after match 1
did go back to 1.55 and there was a slight different set of rules to play with to continue but was able to play more characters, the big similar requirement is not to press buttons til after the CPU attacks you and even then its a compete random chance of the match continuing, not a broken record here but on 1.51 not forced to any of these stipulations, also playing with cheat codes didn't affect the outcome to the testing

**Comment by supersonicjc** [comment] 2018-11-29 08:42
also finding that im forced to reset the game 3 or 4 times to get anywhere in the game plus finding that I can only kick attack the CPU and im finding that to work but never able to get to the credits on newer cores.....

**Comment by bladeoner** [comment] 2018-11-30 11:53
@supersonicjc I'm sorry to say but we won't be able to fix this especially not with the hardware limitations of the Wii.

But I'm curious about something, could you please test the attached file.
What I did is implement the -3 setting from snes9x and I changed the sound to the sound processor used in snes9x. It will sound really bad don't pay attention to that, but I'm curious if you could get further like the PC version.

Thanks in advance for testing.
[Snes9x.GX.4.4.0_S-SMP.zip](https://github.com/dborth/snes9xgx/files/2633086/Snes9x.GX.4.4.0_S-SMP.zip)

**Comment by supersonicjc** [comment] 2018-12-01 14:18
@bladeoner well with that new test beta I fooled around with I got much better results here, only had to reset once and I was able to get all the way to mirror match 3 times before it would freeze didn't even have to go through the strict stipulations I was talking about like on the pc, funny thing too is I quit out of the game and reloaded it and got more results, some could get me to the 3rd match and others got me only past fight 1, I honestly think that unless you have some coding magic under your sleeves I think that is as close as were gonna get on this game which I have to say is much further then the official release on the pc as your not stuck on the stipulations as I mentioned on the earlier post... honestly think weve almost got it fixed but then it tosses me that silly match 1 bug but at least the game is playable even if the ending of it is meh....

**Closed** 2018-12-26 22:50 UTC
