### ISSUE TITLE
Problems with Classic Controller

### ISSUE THREAD

**Issue by NelsonBassanelo** [dborth/snes9xgx#743] opened 2018-08-23 17:03 UTC
Hi there!

I don't speak english so well, but I hope you can understand.

I have a problem with the classic controller (not original from Nintendo) that looks like always press the down button then is impossible to play a game. A few friends said is normal that happen when use a not original controller but I use on USB Loader GX Ver 3.0 Rev 1268, Nitendont ver 5.483, VBA GX ver 2.3.6 and Genesis Plus GX ver 1.7.5 IOS58 and works fine! 

Then I think is weird don't work on that version, I used a previous version of SNES9GX i don't remember which version (probably 4.3.7) and it worked well too, when I updated to 4.3.8 this problem occurred.

Somebody knows what can be?

**Comment by bladeoner** [comment] 2018-08-27 14:45
I use an officia snes controller and I experience that its going up.

I will see if I can figure out what is causing this.

**Comment by NelsonBassanelo** [comment] 2018-08-28 18:35
Hey, I have news... In my case, I use an app that show the buttons that i'm pressing on controller and when I use the Classic Controller this happens:

https://drive.google.com/file/d/1mrkVtDhdhuvjLCndcN4tDBn3XrsnmASN/view?usp=sharing

Appears as if the two analogues are pressed down and left, but the button is perfect with no apparent problems. The strange thing is that in other emulators it works well, even on Wii games that uses these analog (using USB Loader GX).

I noticed that in version 4.3.7 the analogs do not work, maybe they are not mapped or something like that what solves my problem, but I can't use the newer version because of this...

**Comment by bladeoner** [comment] 2018-08-29 18:01
Thank you for your feedback, I looked into it for a moment but couldn't figure out yet what is causing this in the code.

dborth mentioned in #738 that the code is based on:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/gx_input.c
And
https://github.com/mgba-emu/mgba/blob/master/src/platform/wii/main.c

For the time being I'm using my own build were I reverted the commit so the old settings are used, this build is from today including all:
"avoid using file stat when possible. it's slow. "

Please let me know if that works for you now.

[Snes9x.GX.4.3.9.zip](https://github.com/dborth/snes9xgx/files/2333224/Snes9x.GX.4.3.9.zip)

**Comment by NelsonBassanelo** [comment] 2018-08-29 19:10
Hey! Thank you so much! It really worked with no problems, as version 4.3.7 the analogues don't work, right? So works fine for me.

I don't know if other players use the analogue to play but if in the menu they are disabled and on games they are optional to put on configure, I guess this can be a provisional way to stopped that issue.

Once again, thank you! You're the best!

:)

**Comment by bladeoner** [comment] 2018-09-01 20:41
I tried several things out to figure out why it's not working.

I cannot figure out why it is not working but I have the same issue that is going to left-down.

I think you are right that the analog stick was not working and now it is.

**Comment by NelsonBassanelo** [comment] 2018-09-02 17:37
Well then, in that case I think may be useful if had an option to enable/disable the analog stick and by default it come disabled.

I prefer disabled, is more "nostalgic" to play in D pad (and solve my problem with analog stick of course haha) but with that option the people can choose as they like.

:)

**Comment by elbartoscl** [comment] 2018-09-05 02:44
hi everybody. i have the same problem than Nelso Bessanelo, mi classic control dosent work with version 4.3.8 and 4.3.9.  others emulator wor it perfect, even version 4.3.7. it is the same case.

thanks

**Comment by dborth** [comment] 2018-09-08 23:03
I would suggest to try writing a little app to test your controller and have it report some data - maybe even to a file. Others can run it as well (and post results). Then maybe we can sort out the solution. Here's some code to get you started:
https://github.com/corenting/GC-Controller-Test
http://wiibrew.org/wiki/User:Danny/ButtonTracer

I would suggest recording values at stationary positions and then with each direction of the analog pressed. You'll notice the old code uses js.mag and js.ang and the new code uses js.pos.x js.min.x j.max.x js.center.x. So you might want to print all 6 values out

Which is best? What's the solution that will work for all controllers? That's what we're trying to find out.

**Comment by bladeoner** [comment] 2018-09-12 20:12
@dborth thanks for sharing I think with that we can pinpoint the issue and implement a solution to get both analog as dpad working

**Comment by bladeoner** [comment] 2018-11-21 06:38
In the past there were some issues also with the Genesis Plus GX which they fixed by implementing this: https://github.com/ekeeke/Genesis-Plus-GX/commit/bc97990c8712d0a008ac4121026d24bec7d1bd7b#diff-1217e3287328bf9941ffbb34cebe58bf

Tried to implement that in Snes9x GX but it didn't fix the issue.

**Comment by lazlyhu** [comment] 2018-12-02 15:58
@bladeoner Thank you for your support in this issue. 🙇 My controller brand new, just ordered from Ali, so not original. But working great with native Wii games, and in wii menu too.

The button display app show me the same issue mentioned above. The center moved to bottom-left. I attach some screenshot from it.

![img_20181202_161442](https://user-images.githubusercontent.com/25083060/49341781-9574a180-f652-11e8-9385-66d645145c38.jpg)
![img_20181202_161446](https://user-images.githubusercontent.com/25083060/49341782-973e6500-f652-11e8-92af-1bae88dd13cc.jpg)

I tried your patched version of the emulator (linked above) and looks like partially solve the issue. The "permanent scrolling up in the menu" effect disappeared. But I still have some strange issue:
- The most annoying: Looks like sometimes step out to the main menu (of the emulator, so should be a ghost event in "home" button). (I reproduced under mario kart)
- In Tetris I tried, and looks like when I press "down" button, it get a random sideway direction for a minute. And working for other way too, If I press a sideway direction in Dpad, it got a random "down" event too.

If in any way I can help let me know. :)

**Comment by bladeoner** [comment] 2018-12-30 21:59
@dborth I send you a message on the forum about this.

**Comment by dborth** [comment] 2018-12-31 21:35
[controller-test.zip](https://github.com/dborth/snes9xgx/files/2718965/controller-test.zip)

**Comment by dborth** [comment] 2018-12-31 21:36
You can run this testing app and provide the output. Might help devise a solution.

**Closed** 2019-01-01 21:56 UTC

**Comment by lazlyhu** [comment] 2019-01-07 16:07
@dborth @bladeoner The controller working great with the latest release. Thank you very much for your solution! 🥇
